### ISSUE TITLE
Не отображается полный размер файла.

### ISSUE THREAD

**Issue by cheburashkalev** [gtreshchev/RuntimeFilesDownloader#1]
Скачиваю файл с своего веб сервера. Content legth возращает 0

**Comment by cheburashkalev** [comment]
Сам файл скачивается без проблем

**Comment by gtreshchev** [comment]
Hi. I apologize for the inconvenience, there is one small problem due to which this error occurs.

I will fix it shortly.

**Comment by gtreshchev** [comment]
Fixed.
