### ISSUE TITLE
question

### ISSUE THREAD

**Issue by PengChaoJay** [gtreshchev/RuntimeFilesDownloader#10]
I want to know how to download  there is  no mime content type files

**Comment by gtreshchev** [comment]
If you're not certain, you can leave the mine content type field blank, and this will most likely work for you

**Comment by PengChaoJay** [comment]
yes，i leave the content type field blank， but the download file content size is zero，i download the  file by use another way , thank you very mush !!!

**Comment by gtreshchev** [comment]
Thanks for the feedback!

Just to let you know, the plugin has been updated recently to handle the file size better. So, if you're using the GitHub version or the Marketplace (version 5.0 and above), you should be able to get the file's content size for a wider range of server scenarios.
