### ISSUE TITLE
When I try to download a block of files, you actually receive 49 bytes of data, which causes the download to fail

### ISSUE THREAD

**Issue by SIJEYUSES** [gtreshchev/RuntimeFilesDownloader#13]
LogRuntimeFilesDownloader: Downloaded 49 bytes of file chunk from https://internal-api-drive-stream.feishu.cn/space/api/box/stream/download/all/YYF6bdPfEobze3xwXIWcHHqJnVf/?allow_redirect=1. Range: {0; 17}, Overall: 18, Progress: 2.722222
LogRuntimeFilesDownloader: Error: Failed to download file chunk from https://internal-api-drive-stream.feishu.cn/space/api/box/stream/download/all/YYF6bdPfEobze3xwXIWcHHqJnVf/?allow_redirect=1: content length (49) does not match the expected length (18)
LogRuntimeFilesDownloader: Error: Failed to download file chunk from https://internal-api-drive-stream.feishu.cn/space/api/box/stream/download/all/YYF6bdPfEobze3xwXIWcHHqJnVf/?allow_redirect=1: EDownloadToMemoryResult::DownloadFailed
LogRuntimeFilesDownloader: Error: Failed to download file by chunk from https://internal-api-drive-stream.feishu.cn/space/api/box/stream/download/all/YYF6bdPfEobze3xwXIWcHHqJnVf/?allow_redirect=1

**Comment by gtreshchev** [comment]
Should be fixed in 92688c8, please reopen this issue and provide more details if it's still relevant.
