### ISSUE TITLE
Is it possible to add a filepath to OnStorageCompleteEvent?

### ISSUE THREAD

**Issue by stoneHah** [gtreshchev/RuntimeFilesDownloader#15]
I have such a scene：
there aye multi task for download file,when download completed, I will do some processing，after that i want to delete the file

**Comment by VintageDeveloper** [comment]
Hey there. I've added this feature in a pull request. You're welcome to clone this if you'd like to try it: https://github.com/VintageDeveloper/on-event-finish-return-path-string
