### ISSUE TITLE
Files don't appear even though the result is 'Success'

### ISSUE THREAD

**Issue by ShreyasKR8** [gtreshchev/RuntimeFilesDownloader#18]
So I was downloading a file and even though the EDownloadToStorageResult is 'Success' -
![image](https://github.com/gtreshchev/RuntimeFilesDownloader/assets/76420303/c04b3dc0-0515-4474-bc23-b1dd334e29a4)
![image](https://github.com/gtreshchev/RuntimeFilesDownloader/assets/76420303/4d053f3b-ad74-4ee0-96ed-24f64cdc61b9)
As seen in the images, the FilesExists node return false.
This has an impact on unarchiving later using RuntimeArchiver's OpenArchiveFromStorage method. It seems that it is found in the directory after 2 secs. Shouldn't it exist as soon as the EDownloadToStorageResult is a Success?
Can I also get the discord server link as the link in the ReadMe is invalid.

**Comment by gtreshchev** [comment]
As discussed on Discord, the problem was related to the file path used for saving, and you were able to fix this by correcting the path. Closing this issue.

**Comment by ShreyasKR8** [comment]
Can you please send link to your discord server?

**Comment by gtreshchev** [comment]
Hmm, maybe it wasn't you then
Here's the link: https://georgy.dev/discord

**Comment by ShreyasKR8** [comment]
No problem, It got solved. Actually in previous versions we didn't have to
append https:// in download link.but now it seems we need it. Thanks for
the link.
