### ISSUE TITLE
Error when packaging for Linux: Missing precompiled manifest for 'RuntimeFilesDownloader' 

### ISSUE THREAD

**Issue by kubalobo** [gtreshchev/RuntimeFilesDownloader#20]
When trying to build for the Linux Platform, I get the error:
`Missing precompiled manifest for 'RuntimeFilesDownloader'`

It looks like the plugin is missing compiled binaries for Linux?

UE 5.4, plugin installed from Marketplace

**Comment by gtreshchev** [comment]
As far as I'm aware, the Marketplace team only builds binaries for the published products for Windows and Mac, but not for Linux. So, if you want to build the plugin for Linux, you'll need to do it manually. You could download the plugin directly from GitHub into your project's Plugins folder if that's more convenient.

**Comment by kubalobo** [comment]
You are right - adding the plugin to the project `Plugins` folder made it built at the start and solved the problem.

I'm still trying to understand why I do not have to do that with all of the plugins, but maybe Marketplace builds binaries selectively.
I found another approach in the [Cesium plugin](https://github.com/CesiumGS/cesium-unreal/issues/1138#issuecomment-1592441253) - they provide binaries inside the downloadable package from GitHub. Still, it's optional for me, especially as RuntimeFilesDownloader is fast to build.

Thanks!
