### ISSUE TITLE
Error When Build..

### ISSUE THREAD

**Issue by crashangelbr** [gtreshchev/RuntimeFilesDownloader#3]
Hi, I receive this error when Build my project in 4.26.1

` [1/4] Module.RuntimeFilesDownloader.cpp
  X:/MastersUniverse/Plugins/RuntimeFilesDownloader/Source/RuntimeFilesDownloader/Private/RuntimeFilesDownloaderLibrary.cpp(33): error C2440: 'inicializando': não é possível converter de 'TSharedRef<IHttpRequest,ESPMode::ThreadSafe>' para 'TSharedRef<IHttpRequest,ESPMode::NotThreadSafe>'
  X:/MastersUniverse/Plugins/RuntimeFilesDownloader/Source/RuntimeFilesDownloader/Private/RuntimeFilesDownloaderLibrary.cpp(33): note: No builder was able to receive the source type, or builder overhead resolution was ambiguous 
  [2/4] Module.RuntimeFilesDownloader.gen.cpp
`

**Comment by gtreshchev** [comment]
Sorry, I forgot to update the plugin in main GutHub rep.

Fixed.
