### ISSUE TITLE
Default value for timeout is 0 thus breaking current blueprints

### ISSUE THREAD

**Issue by GuillaumeTz** [gtreshchev/RuntimeFilesDownloader#4]
Hello,

All my application broke because the default value for the timeout is 0 when installing newer version of the plugin.

I suggest to add at least a LOG or a callback mechanism for timeout to have some informations also maybe it's possible to have a default value which would work out of the box when adding/updating the node and not break every application out there !

Thanks for the plugin !

**Comment by gtreshchev** [comment]
Hi,
I've added a default value. Thanks you for feedback.
