### ISSUE TITLE
It should be more convenient to output Bytes directly here.

### ISSUE THREAD

**Issue by andiven** [gtreshchev/RuntimeFilesDownloader#5]
![EMDLR8N0C`E}TF)G{5`88GO](https://user-images.githubusercontent.com/91207209/151508630-b8a9d5eb-9494-4f53-a3a2-26306e75c92e.png)

**Comment by gtreshchev** [comment]
You can use the Download File To Memory node
https://github.com/gtreshchev/RuntimeFilesDownloader/wiki

**Comment by andiven** [comment]
oh, I understand. Your idea is to download to memory first, and then use
bytes to connect to the "Save Array to File" node.

Thank you,
Xiaoguang

Georgy Treshchev ***@***.***> 于2022年1月28日周五 17:27写道：
