### ISSUE TITLE
request failed, libcurl error: 18 (Transferred a partial file)

### ISSUE THREAD

**Issue by kithe-raker** [gtreshchev/RuntimeFilesDownloader#7]
I tried to download .pak(unreal pak) file and store it to user's storage by using `DownloadFileToStorage` function.
But most of the time when it downloaded ~40-80%, the download failed. And I got the output log below.

```
LogHttp: Warning: 000001BCC83C7900: request failed, libcurl error: 18 (Transferred a partial file)
LogHttp: Warning: 000001BCC83C7900: libcurl info message cache 0 (Found bundle for host aenalia-ipfs.infura-ipfs.io: 0x1bc30fd2b60 [can pipeline])
LogHttp: Warning: 000001BCC83C7900: libcurl info message cache 1 (Re-using existing connection! (#14) with host aenalia-ipfs.infura-ipfs.io)
LogHttp: Warning: 000001BCC83C7900: libcurl info message cache 2 (Connected to aenalia-ipfs.infura-ipfs.io (52.2.229.63) port 443 (#14))
LogHttp: Warning: 000001BCC83C7900: libcurl info message cache 3 (TLSv1.2 (IN), TLS alert, Client hello (1):)
LogHttp: Warning: 000001BCC83C7900: libcurl info message cache 4 (transfer closed with 13015825 bytes remaining to read)
LogHttp: Warning: 000001BCC83C7900: libcurl info message cache 5 (Closing connection 14)
LogHttp: Warning: 000001BCC83C7900: libcurl info message cache 6 (TLSv1.2 (OUT), TLS alert, Client hello (1):)
LogRuntimeFilesDownloader: Error: An error occurred while downloading the file to storage
LogRuntimeFilesDownloader: Error: Download failed
```

btw I host file on [IPFS](https://docs.ipfs.tech/concepts/how-ipfs-works/), if you want to test, you could use this [url](http://aenalia-ipfs.infura-ipfs.io/ipfs/bafybeifqllrkfc26aiqbfoctbhi2ktm3nt3hzz6dobqyf55vkpafvyothi)
- I've also tried download .pak file from IPFS in the **browser**
- change host to **Firebase Storage** and use `DownloadFileToStorage` normaly
turn out everything is working fine

so I'm not sure if there are something to do with the plugin, or it's just becasue the IPFS itself 🤔

**Comment by gtreshchev** [comment]
Sorry for the late reply. There are several potential issues, e.g. some servers may need more headers to get the correct byte data, or if the file is large enough, some platforms may not be able to handle it directly (in this case, I recommend downloading files by chunks).
