### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by lineCode** [gtreshchev/RuntimeFilesDownloader#9]
https://github.com/gtreshchev/RuntimeFilesDownloader/blob/a92c1c7c4d931a9d125c3b365d8e875288e48f2a/Source/RuntimeFilesDownloader/Private/FileToStorageDownloader.cpp#L5

#include "Editor.h"
build error when package

**Comment by gtreshchev** [comment]
Fixed in 46b616a5552312e2cfbc31df4c58167c4c37c24f, thanks!
